project:
  type: website

website:
  title: "A New Website, second edition"
  navbar:
<<<<<<< HEAD
    left: 
=======
    left:
>>>>>>> a2178cd94a65b2fb23d0aaf509852a3721d1a8c5
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



